sudo: required
language: node_js
node_js:
- 13
deploy:
  provider: heroku
  api_key:
    secure: OxBpQ/7iGv+yMMTdITFqUmqTtEcUNmZgHOXtpcxdY+EkymK8IgKTG9idekY6v2efOEWHBMIbwpkODUEUnZpwolWbcxvYON5lDw4r7LnMm6m36K/H1EoQBQr7tWkx4q6R7AvwmnV96r8s9wpzHwFOX/tHaGeW0cZs3Ay062Xh54Ic20+a4Op7g8DSdzVOFXHJvkEEly8nKICIm+rJJKcYbsH+4zNPgedN1FarRBYmhD4hwcd6BC56ACcBEV2+jttclojweTIawxpAEybOoXD8OK/pHmkiFjd7Oc3iPVwLF8NRVvwTy5F4CP3ha49B4qiW265hgPxEcS+PHxbNc3cLQWuAzt5vf/iUEaukgeIpQxKZvXgRLmG4ToYxkcObFJH2xbc2+gpxMgK4wdPDKouDkMAprI/MAXycBII/tlaIvD9p8bxTVSihjTYk805QD/hsN+U2QNurNSnKZHvi/louGchLe0n9VzgbAxMB9k+gNeyyrbSnjklTtMSMF+bltlioS/dfIJg5vHie+TYvYhfBQxLNzkjX3ZYzFtOSdaZ0Yr0TPTUHuFZGZFczTwlcqQ+TRvsHtrVhcNdNmmUYLvW7D/dmsB+fATOhzRN7uxerhnvgUFZB02NywpslF9GRJ4uzM/Xx+q4cNT+UlNAQwCa5vgyR5Noc12oamhhjmZ8T5u8=
  app:
    master: mysterious-falls-67210
